import { Command } from "commander";
import chalk from "chalk";
import ora from "ora";
import { runScanForSuggest } from "../lib/scan.js";

export function prDescriptionCommand(): Command {
  return new Command("pr-description")
    .description("Generate a PR description for pending dependency upgrades")
    .option("--cwd <path>", "Project directory", process.cwd())
    .option("--clipboard", "Copy output to clipboard (macOS/Linux)")
    .option("--output <file>", "Write to file instead of stdout")
    .option("--title <title>", "PR title override")
    .action(async (options) => {
      const spinner = ora("Scanning for pending upgrades...").start();

      try {
        const data = await runScanForSuggest(options.cwd);
        spinner.stop();

        if (!data || data.outdated.length === 0) {
          console.log(chalk.gray("No outdated dependencies found."));
          return;
        }

        const description = buildPRDescription(data.outdated, data.vulnerabilities, options.title);

        if (options.output) {
          const { writeFileSync } = await import("fs");
          writeFileSync(options.output, description, "utf8");
          console.log(chalk.green(`✔ PR description written to ${options.output}`));
        } else if (options.clipboard) {
          const { exec } = await import("child_process");
          const { promisify } = await import("util");
          const execAsync = promisify(exec);
          try {
            // macOS: pbcopy, Linux: xclip
            const cmd =
              process.platform === "darwin"
                ? `echo ${JSON.stringify(description)} | pbcopy`
                : `echo ${JSON.stringify(description)} | xclip -selection clipboard`;
            await execAsync(cmd);
            console.log(chalk.green("✔ PR description copied to clipboard."));
          } catch {
            process.stdout.write(description + "\n");
            console.log(chalk.yellow("\n(Could not copy to clipboard — output above)"));
          }
        } else {
          process.stdout.write(description + "\n");
        }
      } catch (err) {
        spinner.fail("Failed");
        console.error(err instanceof Error ? err.message : String(err));
        process.exit(1);
      }
    });
}

function buildPRDescription(
  outdated: Array<{ name: string; current: string; latest: string; type?: string }>,
  vulns: unknown,
  titleOverride?: string
): string {
  const vulnCount = (vulns as any)?.totalCount ?? (vulns as any)?.vulnerabilityCount ?? 0;
  const criticalCount = (vulns as any)?.criticalCount ?? 0;

  // Separate major vs minor/patch
  const major: typeof outdated = [];
  const minorPatch: typeof outdated = [];
  for (const pkg of outdated) {
    const curMajor = parseInt(pkg.current.replace(/[^0-9]/, ""), 10);
    const latMajor = parseInt(pkg.latest.replace(/[^0-9]/, ""), 10);
    if (!isNaN(curMajor) && !isNaN(latMajor) && latMajor > curMajor) {
      major.push(pkg);
    } else {
      minorPatch.push(pkg);
    }
  }

  const title =
    titleOverride ??
    (major.length > 0
      ? `chore: upgrade ${major
          .slice(0, 2)
          .map((p) => p.name)
          .join(", ")}${major.length > 2 ? ` and ${major.length - 2} more` : ""} (major)`
      : `chore: update ${outdated.length} dependenc${outdated.length !== 1 ? "ies" : "y"} (minor/patch)`);

  const lines: string[] = [];
  lines.push(`## ${title}`);
  lines.push("");

  if (vulnCount > 0) {
    lines.push(
      `> ⚠️ This update addresses **${vulnCount} security vulnerability${vulnCount !== 1 ? "ies" : "y"}**${criticalCount > 0 ? ` (${criticalCount} critical)` : ""}.`
    );
    lines.push("");
  }

  lines.push("### What changed");
  lines.push("");

  if (major.length > 0) {
    lines.push("**Major upgrades** (may contain breaking changes — review changelog before merging):");
    lines.push("");
    for (const pkg of major) {
      lines.push(
        `- \`${pkg.name}\` ${pkg.current} → **${pkg.latest}** ([changelog](https://www.npmjs.com/package/${pkg.name}?activeTab=versions))`
      );
    }
    lines.push("");
  }

  if (minorPatch.length > 0) {
    lines.push(`**Minor / patch upgrades** (${minorPatch.length} package${minorPatch.length !== 1 ? "s" : ""}):`);
    lines.push("");
    for (const pkg of minorPatch) {
      lines.push(`- \`${pkg.name}\` ${pkg.current} → ${pkg.latest}`);
    }
    lines.push("");
  }

  lines.push("### Testing");
  lines.push("");
  lines.push("- [ ] `npm test` passes");
  lines.push("- [ ] No runtime errors in dev");
  if (major.length > 0) lines.push("- [ ] Breaking change migration guide reviewed for each major upgrade");
  lines.push("- [ ] Dependency audit clean: `upshift audit`");
  lines.push("");
  lines.push("---");
  lines.push("*Generated by [Upshift CLI](https://upshiftai.dev) — `upshift pr-description`*");

  return lines.join("\n");
}
