import { Command } from "commander";
import chalk from "chalk";
import * as fs from "fs";
import * as path from "path";

export function scheduleCommand(): Command {
  const cmd = new Command("schedule");
  cmd.description("Generate and install scheduled dependency scan workflows");

  cmd.addCommand(generateSubcommand());
  cmd.addCommand(installSubcommand());

  // Default action when called with no subcommand — show help
  cmd.action(() => cmd.help());

  return cmd;
}

function addSharedOptions(cmd: Command): Command {
  return cmd
    .option("--cron <expression>", "Cron schedule expression", "0 9 * * 1")
    .option("--notify-slack", "Include Slack notification step")
    .option("--notify-discord", "Include Discord notification step")
    .option("--branch <branch>", "Branch to scan", "main")
    .option("--node <version>", "Node.js version", "20")
    .option("--ai", "Include AI-powered scan step (uses 1 credit per run)");
}

function generateSubcommand(): Command {
  const cmd = new Command("generate");
  cmd.description("Print a GitHub Actions workflow YAML to stdout or write to file");

  addSharedOptions(cmd);
  cmd.option("--output <file>", "Write to file instead of stdout");

  cmd.action((options) => {
    const yaml = buildWorkflowYaml(options);

    if (options.output) {
      const outPath = path.resolve(options.output);
      fs.writeFileSync(outPath, yaml, "utf8");
      console.log(chalk.green("✔") + " Workflow written to " + chalk.cyan(options.output));
    } else {
      process.stdout.write(yaml);
    }
  });

  return cmd;
}

function installSubcommand(): Command {
  const cmd = new Command("install");
  cmd.description("Write the workflow to .github/workflows/upshift.yml");

  addSharedOptions(cmd);
  cmd.option("--cwd <path>", "Project directory", process.cwd());
  cmd.option("--force", "Overwrite if file already exists");

  cmd.action((options) => {
    const cwd = options.cwd ?? process.cwd();
    const workflowDir = path.join(cwd, ".github", "workflows");
    const workflowPath = path.join(workflowDir, "upshift.yml");
    const displayPath = path.join(".github", "workflows", "upshift.yml");

    if (fs.existsSync(workflowPath) && !options.force) {
      console.error(
        chalk.red("Error:") +
          " Workflow file already exists at " +
          chalk.cyan(displayPath) +
          "\n" +
          "Use " +
          chalk.cyan("--force") +
          " to overwrite."
      );
      process.exit(1);
    }

    if (!fs.existsSync(workflowDir)) {
      fs.mkdirSync(workflowDir, { recursive: true });
    }

    const yaml = buildWorkflowYaml(options);
    fs.writeFileSync(workflowPath, yaml, "utf8");

    const schedDesc = cronDescription(options.cron);

    console.log(chalk.green("✔") + " Workflow written to " + chalk.cyan(displayPath));
    console.log();
    console.log("Next steps:");
    console.log(
      "  1. Add your API token to GitHub Secrets:\n" +
        "       Settings → Secrets → " +
        chalk.cyan("UPSHIFT_API_TOKEN") +
        "\n" +
        "       Get token: " +
        chalk.gray("https://upshift.dev/dashboard/settings")
    );
    console.log();
    console.log(
      "  2. Commit the workflow file:\n" +
        "       " +
        chalk.cyan('git add .github/workflows/upshift.yml && git commit -m "ci: add Upshift dependency scan"')
    );
    console.log();
    console.log(
      "  3. Push and watch it run:\n" +
        "       " +
        chalk.cyan("git push") +
        "\n" +
        "       → GitHub Actions will run on: " +
        chalk.white(schedDesc)
    );
    console.log();
    console.log(
      chalk.yellow("💡") + " Run " + chalk.cyan("`upshift notify --test`") + " to verify your notification channels."
    );
  });

  return cmd;
}

interface WorkflowOptions {
  cron: string;
  notifySlack?: boolean;
  notifyDiscord?: boolean;
  branch: string;
  node: string;
  ai?: boolean;
}

function buildWorkflowYaml(options: WorkflowOptions): string {
  const schedDesc = cronDescription(options.cron);

  const notifySlackStep = options.notifySlack
    ? `
      - name: Notify Slack
        if: always()
        env:
          UPSHIFT_SLACK_WEBHOOK: \${{ secrets.UPSHIFT_SLACK_WEBHOOK }}
          UPSHIFT_API_TOKEN: \${{ secrets.UPSHIFT_API_TOKEN }}
        run: upshift notify --slack "\${{ secrets.UPSHIFT_SLACK_WEBHOOK }}"
`
    : "";

  const notifyDiscordStep = options.notifyDiscord
    ? `
      - name: Notify Discord
        if: always()
        env:
          UPSHIFT_DISCORD_WEBHOOK: \${{ secrets.UPSHIFT_DISCORD_WEBHOOK }}
          UPSHIFT_API_TOKEN: \${{ secrets.UPSHIFT_API_TOKEN }}
        run: upshift notify --discord "\${{ secrets.UPSHIFT_DISCORD_WEBHOOK }}"
`
    : "";

  return `# Upshift — Automated Dependency Scan
# Generated by: upshift schedule install
# Docs: https://upshift.dev/docs/ci
name: Upshift Dependency Scan

on:
  schedule:
    - cron: "${options.cron}" # ${schedDesc}
  workflow_dispatch: # allow manual runs
  push:
    branches: ["${options.branch}"]
    paths:
      - "package.json"
      - "package-lock.json"
      - "yarn.lock"
      - "pnpm-lock.yaml"

jobs:
  upshift-scan:
    name: Dependency Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # for future PR comment support

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${options.node}"
          cache: "npm"

      - name: Install Upshift CLI
        run: npm install -g upshift-cli

      - name: Run Dependency Scan
        env:
          UPSHIFT_API_TOKEN: \${{ secrets.UPSHIFT_API_TOKEN }}
        run: upshift scan --report upshift-report.json${options.ai ? " --ai" : ""}

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: upshift-report
          path: upshift-report.json
          retention-days: 30
${notifySlackStep}${notifyDiscordStep}
# ─────────────────────────────────────────────
# Required GitHub Secrets:
#   UPSHIFT_API_TOKEN  — from https://upshift.dev/dashboard/settings
# Optional secrets:
#   UPSHIFT_SLACK_WEBHOOK  — Slack incoming webhook URL
#   UPSHIFT_DISCORD_WEBHOOK — Discord webhook URL
# ─────────────────────────────────────────────
`;
}

function cronDescription(cron: string): string {
  switch (cron) {
    case "0 9 * * 1":
      return "Mondays at 9am UTC";
    case "0 9 * * *":
      return "Daily at 9am UTC";
    case "0 9 * * 1-5":
      return "Weekdays at 9am UTC";
    case "0 0 1 * *":
      return "1st of each month at midnight UTC";
    default:
      return `Custom schedule: ${cron}`;
  }
}
